#include <jni.h>
#include <android/log.h>
#include <android/bitmap.h>
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../jpeg8d/jpeglib.h"

#define  LOG_TAG    "MJPEG"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

#define abs_mcr(x) ((x)>0 ? (x) : -(x))

int IMG_WIDTH=-1;
int IMG_HEIGHT=-1;

int *rgb=NULL;

/* for libjpeg */
typedef struct {
  struct jpeg_source_mgr pub;/* public fields */
  int skip;
} memory_source_mgr;
typedef memory_source_mgr *memory_src_ptr;

struct my_error_mgr {
  struct jpeg_error_mgr pub;
  jmp_buf setjmp_buffer;
};

typedef struct my_error_mgr * my_error_ptr;

METHODDEF(void) my_error_exit (j_common_ptr cinfo);
GLOBAL(void) jpeg_memory_src (j_decompress_ptr cinfo, void* data, unsigned long len);
METHODDEF(void) memory_init_source (j_decompress_ptr cinfo);
METHODDEF(boolean) memory_fill_input_buffer (j_decompress_ptr cinfo);
METHODDEF(void) memory_skip_input_data (j_decompress_ptr cinfo, long num_bytes);
METHODDEF(void) memory_term_source (j_decompress_ptr cinfo);
/* end of libjpeg */


void processimage (const void *p, int l);

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream */

#ifndef _Included_com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream
#define _Included_com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_MAX_SKIP_BUFFER_SIZE
#define com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_HEADER_MAX_LENGTH
#define com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_HEADER_MAX_LENGTH 100L
#undef com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_FRAME_MAX_LENGTH
#define com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_FRAME_MAX_LENGTH 200000L
#undef com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_DEBUG
#define com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_DEBUG 0L
/*
 * Class:     com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream
 * Method:    pixeltobmp
 * Signature: ([BILandroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_pixeltobmp
  (JNIEnv *, jobject, jbyteArray, jint, jobject);

/*
 * Class:     com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream
 * Method:    freeCameraMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_greenenergyresearch_jamesfolk_datalogger_MjpegInputStream_freeCameraMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

